import { colors } from "@/styles/global";
import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 32,
    paddingLeft: 16,
    paddingRight: 16,
    alignItems: "center",
    width: "100%",
    height: "100%",
    backgroundColor: colors.white,
    borderRadius: 8,
  },
  wrapper: {
    gap: 8,
    marginBottom: 32,
  },
  imageWrapper: {
    position: "relative",
    width: "100%",
    height: 240,
    backgroundColor: colors.input_border_color,
    borderRadius: 8,
  },
  image: {
    minWidth: "100%",
  },
  imageButton: {
    position: "absolute",
    left: "50%",
    top: "50%",
    transform: [{ translateX: -30 }, { translateY: -30 }],
    height: 60,
    width: 60,
    borderRadius: 50,
    backgroundColor: colors.white,
    justifyContent: "center",
    alignItems: "center",
  },
  imageButtonReady: {
    backgroundColor: "rgba(255, 255, 255, 0.3)",
  },
  buttonIcon: {
    width: 24,
    height: 24,
    tintColor: colors.grey_text_color,
  },
  buttonIconReady: {
    tintColor: colors.white,
  },
  text: {
    color: colors.grey_text_color,
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    lineHeight: 19,
    fontWeight: "400",
    textAlign: "left",
  },
  textInput: {
    height: 50,
    width: "100%",
    paddingVertical: 0,
    paddingHorizontal: 8,
    borderBottomColor: colors.input_border_color,
    borderBottomWidth: 1,
    borderStyle: "solid",
    color: colors.text_color_black,
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    lineHeight: 19,
    fontWeight: "400",
    textAlign: "left",
  },
  textInputMap: {
    borderBottomWidth: 0,
    marginBottom: 0,
  },
  textInputFocused: {
    borderBottomColor: colors.orange_color,
    color: colors.text_color_black,
  },
  mapWrapper: {
    marginTop: 16,
    flexDirection: "row",
    width: "100%",
    alignItems: "center",
    borderBottomColor: colors.input_border_color,
    borderBottomWidth: 1,
    borderStyle: "solid",
  },
  mapIcon: {
    width: 24,
    height: 24,
    marginRight: 8,
    tintColor: colors.grey_text_color,
  },
  buttonSubmit: {
    height: 50,
    marginTop: 32,
    width: "100%",
    borderRadius: 100,
    backgroundColor: colors.input_bg_color,
    justifyContent: "center",
    alignItems: "center",
  },
  buttonSubmitReady: {
    backgroundColor: colors.orange_color,
  },
  buttonSubmitText: {
    color: colors.grey_text_color,
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    lineHeight: 19,
    fontWeight: "400",
    textAlign: "center",
  },
  buttonSubmitTextReady: {
    color: colors.white,
  },
  buttonDelete: {
    marginTop: 120,
    height: 40,
    width: 70,
    borderRadius: 50,
    backgroundColor: colors.input_bg_color,
    justifyContent: "center",
    alignItems: "center",
  },
  buttonDeleteIcon: {
    color: colors.grey_text_color,
  },
});
